### ISSUE TITLE
RMSE

### ISSUE THREAD

**Issue by yazan-alomari1** [jiaxiang-cheng/PyTorch-Transformer-for-RUL-Prediction#11]
Hello, 

firstly, thank you for your code, it's awesome. 

I have run the code without any changes, but I haven't got the same RMSE as yours. 
is there any change I must do before run ?

**Comment by jiaxiang-cheng** [comment]
> Hello,
> 
> firstly, thank you for your code, it's awesome.
> 
> I have run the code without any changes, but I haven't got the same RMSE as yours. is there any change I must do before run ?

Hi Thanks for your acknowledgment. The implementation serves only as an initial step, which you could further improve in many different ways. The RMSE is also not the latest one I got, which is already much better than the showed. But those improvements not published so I can't really upload here yet. But maybe soon :)
