### ISSUE TITLE
CMAPSS的结果

### ISSUE THREAD

**Issue by iamownt** [jiaxiang-cheng/PyTorch-Transformer-for-RUL-Prediction#4]
从这篇论文"KDnet-RUL: A Knowledge Distillation Framework to Compress Deep Neural Networks for Machine Remaining Useful Life Prediction"。 FD002 14.47. FD004 15.96. 它的FD002和FD004效果很好，你可以复现类似的结果吗。我看你复现的这个论文结果FD002 22.81 FD004 24.86并不好。想follow一下，感觉follow了一个大坑。

**Comment by jiaxiang-cheng** [comment]
> 从这篇论文"KDnet-RUL: A Knowledge Distillation Framework to Compress Deep Neural Networks for Machine Remaining Useful Life Prediction"。 FD002 14.47. FD004 15.96. 它的FD002和FD004效果很好，你可以复现类似的结果吗。我看你复现的这个论文结果FD002 22.81 FD004 24.86并不好。想follow一下，感觉follow了一个大坑。

您好，您可以自己尝试复现您觉得好的文章。
